import type { AssessmentItem, StageAssessment } from '../types.js';

export const cognitiveAmber: StageAssessment = {
  line: 'Cognitive',
  stage: 'Amber',
  tasks: [
    {
      id: 'cog-amb-nback2',
      type: 'n_back',
      description: 'N=2 stable n-back with consistent rule application',
      parameters: { n: 2, trials: 14, stimulusDurationMs: 1000, interStimulusMs: 400 },
      measures: ['accuracy', 'response_time', 'consistency'],
    },
    {
      id: 'cog-amb-stroop',
      type: 'stroop',
      description: 'Stroop interference: name color not word',
      parameters: { trials: 16, congruentRatio: 0.5, stimulusDurationMs: 2000 },
      measures: ['accuracy', 'response_time'],
    },
    {
      id: 'cog-amb-gonogo',
      type: 'go_no_go',
      description: 'WCST low switch: maintain rule across trials',
      parameters: { goRatio: 0.75, trials: 20, stimulusDurationMs: 600, switchFrequency: 'low' },
      measures: ['accuracy', 'response_time', 'self_correction'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.6,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      complexity_handled: 0.3,
      self_correction: 0.2,
    },
  },
  minimumTrials: 5,
  estimatedDurationMs: 240000,
  itemPool: [
    { id: 'cognitive-amber-01', taskType: 'n_back', difficulty: 0.2, parameters: { n: 2, trials: 8, stimulusDurationMs: 1200, interStimulusMs: 450 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-amber-02', taskType: 'n_back', difficulty: 0.25, parameters: { n: 2, trials: 10, stimulusDurationMs: 1100, interStimulusMs: 420 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-amber-03', taskType: 'n_back', difficulty: 0.3, parameters: { n: 3, trials: 8, stimulusDurationMs: 1200, interStimulusMs: 450 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-amber-04', taskType: 'n_back', difficulty: 0.35, parameters: { n: 3, trials: 10, stimulusDurationMs: 1100, interStimulusMs: 400 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-amber-05', taskType: 'n_back', difficulty: 0.4, parameters: { n: 3, trials: 12, stimulusDurationMs: 1000, interStimulusMs: 380 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-amber-06', taskType: 'stroop', difficulty: 0.3, parameters: { trials: 10, congruentRatio: 0.6, stimulusDurationMs: 2200, ruleType: 'color-word' }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-amber-07', taskType: 'stroop', difficulty: 0.4, parameters: { trials: 14, congruentRatio: 0.5, stimulusDurationMs: 2000, ruleType: 'color-word' }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-amber-08', taskType: 'stroop', difficulty: 0.5, parameters: { trials: 16, congruentRatio: 0.4, stimulusDurationMs: 1800, ruleType: 'category-switch' }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-amber-09', taskType: 'go_no_go', difficulty: 0.35, parameters: { goRatio: 0.75, trials: 16, stimulusDurationMs: 700, switchFrequency: 'low' }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-amber-10', taskType: 'go_no_go', difficulty: 0.45, parameters: { goRatio: 0.7, trials: 20, stimulusDurationMs: 600, switchFrequency: 'low' }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-amber-11', taskType: 'go_no_go', difficulty: 0.55, parameters: { goRatio: 0.7, trials: 24, stimulusDurationMs: 550, switchFrequency: 'medium' }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-amber-12', taskType: 'n_back', difficulty: 0.5, parameters: { n: 3, trials: 14, stimulusDurationMs: 950, interStimulusMs: 350 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-amber-13', taskType: 'pattern_prediction', difficulty: 0.5, parameters: { disks: 4, maxMoves: 4, attempts: 4, ruleBasedCategories: 3 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-amber-14', taskType: 'pattern_prediction', difficulty: 0.6, parameters: { disks: 5, maxMoves: 5, attempts: 3, ruleBasedCategories: 4 }, measures: ['accuracy', 'complexity_handled', 'self_correction'] },
    { id: 'cognitive-amber-15', taskType: 'n_back', difficulty: 0.6, parameters: { n: 3, trials: 16, stimulusDurationMs: 900, interStimulusMs: 320 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-amber-16', taskType: 'n_back', difficulty: 0.65, parameters: { n: 4, trials: 10, stimulusDurationMs: 1100, interStimulusMs: 400 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-amber-17', taskType: 'n_back', difficulty: 0.7, parameters: { n: 4, trials: 12, stimulusDurationMs: 1000, interStimulusMs: 350 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-amber-18', taskType: 'stroop', difficulty: 0.75, parameters: { trials: 20, congruentRatio: 0.35, stimulusDurationMs: 1500, ruleType: 'multi-rule-switch' }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-amber-19', taskType: 'n_back', difficulty: 0.85, parameters: { n: 4, trials: 14, stimulusDurationMs: 900, interStimulusMs: 300 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-amber-20', taskType: 'n_back', difficulty: 0.9, parameters: { n: 4, trials: 16, stimulusDurationMs: 850, interStimulusMs: 280 }, measures: ['accuracy', 'response_time', 'self_correction', 'complexity_handled'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Complete Stroop without timing pressure',
      task: {
        id: 'cog-amb-probe-agency',
        type: 'stroop',
        description: 'Stroop task without external timing pressure',
        parameters: { trials: 8, congruentRatio: 0.5, stimulusDurationMs: 3000, selfPaced: true },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Applies rule consistently with own pacing',
      addictionSignal: 'Rigidly applies rule, cannot flex',
      allergySignal: 'Cannot apply rule without external structure',
    },
    communion: {
      description: 'Explain rule-following strategy to NPC',
      task: {
        id: 'cog-amb-probe-communion',
        type: 'llm_dialogue',
        description: 'Explain how you follow the rule to NPC learner',
        parameters: { prompt: 'How do you know which rule to follow?', maxResponseLength: 300 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares strategy without losing own approach',
      addictionSignal: 'Imposes rule on other without flexibility',
      allergySignal: 'Cannot explain own process to another',
    },
    eros: {
      description: 'Attempt rule-switching at higher frequency',
      task: {
        id: 'cog-amb-probe-eros',
        type: 'go_no_go',
        description: 'Go/No-Go with higher switch frequency',
        parameters: { goRatio: 0.7, trials: 12, stimulusDurationMs: 500, switchFrequency: 'medium' },
        measures: ['accuracy', 'response_time', 'self_correction'],
      },
      healthyResponse: 'Reaches toward faster switching with curiosity',
      addictionSignal: 'Compulsively switches, cannot maintain stable rule',
      allergySignal: 'Refuses any rule change, clings to single rule',
    },
    agape: {
      description: 'Return to n=1 with full presence and rule clarity',
      task: {
        id: 'cog-amb-probe-agape',
        type: 'n_back',
        description: 'Return to n=1 n-back with full presence',
        parameters: { n: 1, trials: 6, stimulusDurationMs: 1500, interStimulusMs: 500 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple rule with care and presence',
      addictionSignal: 'Refuses simple tasks as beneath them',
      allergySignal: 'Cannot engage even at simple level',
    },
  },
};
