import type { AssessmentItem, StageAssessment } from '../types.js';

export const cognitiveMagenta: StageAssessment = {
  line: 'Cognitive',
  stage: 'Magenta',
  tasks: [
    {
      id: 'cog-mag-nback1',
      type: 'n_back',
      description: 'N=1 n-back: identify immediate repeat',
      parameters: { n: 1, trials: 10, stimulusDurationMs: 1500, interStimulusMs: 500 },
      measures: ['accuracy', 'response_time', 'consistency'],
    },
    {
      id: 'cog-mag-pattern',
      type: 'pattern_prediction',
      description: 'Simple pattern completion: A-B-A-?',
      parameters: { patternLength: 3, patternType: 'alternating', trials: 6 },
      measures: ['accuracy', 'complexity_handled'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.5,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      complexity_handled: 0.3,
      self_correction: 0.2,
    },
  },
  minimumTrials: 4,
  estimatedDurationMs: 120000,
  itemPool: [
    { id: 'cognitive-magenta-01', taskType: 'pattern_prediction', difficulty: 0.2, parameters: { patternLength: 2, patternType: 'simple-repeat', trials: 4 }, measures: ['accuracy'] },
    { id: 'cognitive-magenta-02', taskType: 'pattern_prediction', difficulty: 0.25, parameters: { patternLength: 2, patternType: 'alternating', trials: 4 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-magenta-03', taskType: 'n_back', difficulty: 0.25, parameters: { n: 1, trials: 6, stimulusDurationMs: 1800, interStimulusMs: 600 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-magenta-04', taskType: 'pattern_prediction', difficulty: 0.3, parameters: { patternLength: 3, patternType: 'alternating', trials: 5 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-magenta-05', taskType: 'n_back', difficulty: 0.3, parameters: { n: 1, trials: 8, stimulusDurationMs: 1600, interStimulusMs: 550 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-magenta-06', taskType: 'pattern_prediction', difficulty: 0.35, parameters: { patternLength: 3, patternType: 'alternating', trials: 6 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-magenta-07', taskType: 'n_back', difficulty: 0.4, parameters: { n: 1, trials: 10, stimulusDurationMs: 1500, interStimulusMs: 500 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-magenta-08', taskType: 'pattern_prediction', difficulty: 0.4, parameters: { patternLength: 3, patternType: 'cause-effect', trials: 5 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-magenta-09', taskType: 'n_back', difficulty: 0.45, parameters: { n: 1, trials: 12, stimulusDurationMs: 1400, interStimulusMs: 480 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-magenta-10', taskType: 'pattern_prediction', difficulty: 0.5, parameters: { patternLength: 4, patternType: 'repeating', trials: 5 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-magenta-11', taskType: 'n_back', difficulty: 0.5, parameters: { n: 1, trials: 14, stimulusDurationMs: 1300, interStimulusMs: 450 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-magenta-12', taskType: 'pattern_prediction', difficulty: 0.55, parameters: { patternLength: 4, patternType: 'cause-effect', trials: 6 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-magenta-13', taskType: 'n_back', difficulty: 0.55, parameters: { n: 2, trials: 6, stimulusDurationMs: 1600, interStimulusMs: 550 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-magenta-14', taskType: 'pattern_prediction', difficulty: 0.6, parameters: { patternLength: 5, patternType: 'repeating', trials: 5 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-magenta-15', taskType: 'n_back', difficulty: 0.65, parameters: { n: 2, trials: 8, stimulusDurationMs: 1500, interStimulusMs: 500 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-magenta-16', taskType: 'pattern_prediction', difficulty: 0.7, parameters: { patternLength: 5, patternType: 'cause-effect', trials: 6 }, measures: ['accuracy', 'complexity_handled', 'self_correction'] },
    { id: 'cognitive-magenta-17', taskType: 'n_back', difficulty: 0.75, parameters: { n: 2, trials: 10, stimulusDurationMs: 1400, interStimulusMs: 450 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-magenta-18', taskType: 'pattern_prediction', difficulty: 0.8, parameters: { patternLength: 5, patternType: 'multi-cause', trials: 6 }, measures: ['accuracy', 'complexity_handled', 'self_correction'] },
    { id: 'cognitive-magenta-19', taskType: 'n_back', difficulty: 0.85, parameters: { n: 2, trials: 12, stimulusDurationMs: 1300, interStimulusMs: 420 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-magenta-20', taskType: 'n_back', difficulty: 0.9, parameters: { n: 2, trials: 14, stimulusDurationMs: 1200, interStimulusMs: 400 }, measures: ['accuracy', 'response_time', 'consistency', 'self_correction'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Complete n=1 without hints or prompts',
      task: {
        id: 'cog-mag-probe-agency',
        type: 'n_back',
        description: 'N-back n=1 without hints',
        parameters: { n: 1, trials: 5, stimulusDurationMs: 1500, interStimulusMs: 500, hintsEnabled: false },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Engages independently with simple memory task',
      addictionSignal: 'Refuses any assistance or connection',
      allergySignal: 'Cannot attempt without guarantee of success',
    },
    communion: {
      description: 'Explain pattern to NPC friend',
      task: {
        id: 'cog-mag-probe-communion',
        type: 'llm_dialogue',
        description: 'Explain A-B-A pattern to an NPC friend',
        parameters: { prompt: 'What comes next in the pattern?', maxResponseLength: 200 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares thinking with simple language',
      addictionSignal: 'Cannot hold own understanding while sharing',
      allergySignal: 'Refuses to share or explain',
    },
    eros: {
      description: 'Attempt a longer pattern (A-B-C-A-B-?)',
      task: {
        id: 'cog-mag-probe-eros',
        type: 'pattern_prediction',
        description: 'Attempt longer three-element repeating pattern',
        parameters: { patternLength: 5, patternType: 'repeating', trials: 4 },
        measures: ['accuracy', 'complexity_handled'],
      },
      healthyResponse: 'Reaches toward harder pattern with curiosity',
      addictionSignal: 'Compulsively seeks harder patterns',
      allergySignal: 'Refuses to try beyond simple alternation',
    },
    agape: {
      description: 'Return to simplest A-B-A with full engagement',
      task: {
        id: 'cog-mag-probe-agape',
        type: 'pattern_prediction',
        description: 'Return to simplest alternating pattern',
        parameters: { patternLength: 3, patternType: 'alternating', trials: 3 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple pattern with care and attention',
      addictionSignal: 'Refuses simple patterns as beneath them',
      allergySignal: 'Cannot engage with patterns at all',
    },
  },
};
