import type { AssessmentItem, StageAssessment } from '../types.js';

export const cognitiveRed: StageAssessment = {
  line: 'Cognitive',
  stage: 'Red',
  tasks: [
    {
      id: 'cog-red-nback2',
      type: 'n_back',
      description: 'Hold 2 items in working memory and identify matches',
      parameters: { n: 2, trials: 12, stimulusDurationMs: 1100, interStimulusMs: 350 },
      measures: ['accuracy', 'response_time', 'consistency'],
    },
    {
      id: 'cog-red-planning',
      type: 'pattern_prediction',
      description: '2-step planning task (Tower of London with 3 disks)',
      parameters: { disks: 3, maxMoves: 2, attempts: 4 },
      measures: ['accuracy', 'complexity_handled', 'self_correction'],
    },
    {
      id: 'cog-red-gonogo',
      type: 'go_no_go',
      description: 'Go/No-Go inhibition task',
      parameters: { goRatio: 0.7, trials: 20, stimulusDurationMs: 500 },
      measures: ['accuracy', 'response_time'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.6,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      complexity_handled: 0.3,
      self_correction: 0.2,
    },
  },
  minimumTrials: 4,
  estimatedDurationMs: 180000,
  itemPool: [
    { id: 'cognitive-red-01', taskType: 'n_back', difficulty: 0.2, parameters: { n: 1, trials: 8, stimulusDurationMs: 1200, interStimulusMs: 400 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-red-02', taskType: 'n_back', difficulty: 0.25, parameters: { n: 1, trials: 10, stimulusDurationMs: 1100, interStimulusMs: 380 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-red-03', taskType: 'n_back', difficulty: 0.3, parameters: { n: 2, trials: 8, stimulusDurationMs: 1200, interStimulusMs: 400 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-red-04', taskType: 'n_back', difficulty: 0.35, parameters: { n: 2, trials: 10, stimulusDurationMs: 1100, interStimulusMs: 380 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-red-05', taskType: 'n_back', difficulty: 0.4, parameters: { n: 2, trials: 12, stimulusDurationMs: 1000, interStimulusMs: 350 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-red-06', taskType: 'pattern_prediction', difficulty: 0.3, parameters: { disks: 3, maxMoves: 2, attempts: 3 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-red-07', taskType: 'pattern_prediction', difficulty: 0.4, parameters: { disks: 3, maxMoves: 3, attempts: 4 }, measures: ['accuracy', 'complexity_handled', 'self_correction'] },
    { id: 'cognitive-red-08', taskType: 'pattern_prediction', difficulty: 0.5, parameters: { disks: 4, maxMoves: 3, attempts: 4 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-red-09', taskType: 'n_back', difficulty: 0.5, parameters: { n: 2, trials: 14, stimulusDurationMs: 950, interStimulusMs: 320 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-red-10', taskType: 'n_back', difficulty: 0.55, parameters: { n: 2, trials: 16, stimulusDurationMs: 900, interStimulusMs: 300 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-red-11', taskType: 'pattern_prediction', difficulty: 0.55, parameters: { disks: 4, maxMoves: 4, attempts: 3 }, measures: ['accuracy', 'complexity_handled', 'self_correction'] },
    { id: 'cognitive-red-12', taskType: 'n_back', difficulty: 0.6, parameters: { n: 3, trials: 8, stimulusDurationMs: 1100, interStimulusMs: 350 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-red-13', taskType: 'n_back', difficulty: 0.65, parameters: { n: 3, trials: 10, stimulusDurationMs: 1000, interStimulusMs: 320 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-red-14', taskType: 'pattern_prediction', difficulty: 0.6, parameters: { disks: 4, maxMoves: 5, attempts: 3 }, measures: ['complexity_handled', 'self_correction'] },
    { id: 'cognitive-red-15', taskType: 'n_back', difficulty: 0.7, parameters: { n: 3, trials: 12, stimulusDurationMs: 950, interStimulusMs: 300 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-red-16', taskType: 'pattern_prediction', difficulty: 0.7, parameters: { disks: 5, maxMoves: 4, attempts: 3 }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-red-17', taskType: 'n_back', difficulty: 0.75, parameters: { n: 3, trials: 14, stimulusDurationMs: 900, interStimulusMs: 280 }, measures: ['accuracy', 'response_time', 'self_correction'] },
    { id: 'cognitive-red-18', taskType: 'pattern_prediction', difficulty: 0.8, parameters: { disks: 5, maxMoves: 5, attempts: 2 }, measures: ['complexity_handled', 'self_correction'] },
    { id: 'cognitive-red-19', taskType: 'n_back', difficulty: 0.85, parameters: { n: 3, trials: 16, stimulusDurationMs: 850, interStimulusMs: 260 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-red-20', taskType: 'n_back', difficulty: 0.9, parameters: { n: 4, trials: 10, stimulusDurationMs: 900, interStimulusMs: 300 }, measures: ['accuracy', 'response_time', 'self_correction', 'complexity_handled'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Complete n=2 without hints',
      task: {
        id: 'cog-red-probe-agency',
        type: 'n_back',
        description: 'N-back task without help indicators',
        parameters: { n: 2, trials: 6, stimulusDurationMs: 1100, interStimulusMs: 350, hintsEnabled: false },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Sovereign thinking - solved independently',
      addictionSignal: 'Refuses all input, cognitive aggression',
      allergySignal: 'Cannot attempt without guarantee',
    },
    communion: {
      description: 'Explain strategy to NPC companion',
      task: {
        id: 'cog-red-probe-communion',
        type: 'llm_dialogue',
        description: 'Explain n-back strategy to NPC companion',
        parameters: { prompt: 'Can you explain how you remember the items?', maxResponseLength: 300 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares thinking without losing approach',
      addictionSignal: 'Hoards strategy, refuses sharing',
      allergySignal: 'Adopts others strategies without understanding',
    },
    eros: {
      description: 'Attempt n=3 (above current level)',
      task: {
        id: 'cog-red-probe-eros',
        type: 'n_back',
        description: 'N-back task at n=3, above current assessed level',
        parameters: { n: 3, trials: 6, stimulusDurationMs: 1100, interStimulusMs: 350 },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Reaches toward complexity with curiosity',
      addictionSignal: 'Compulsive reaching, cannot rest',
      allergySignal: 'Refuses growth, treats edge as threatening',
    },
    agape: {
      description: 'Do n=1 again with full engagement',
      task: {
        id: 'cog-red-probe-agape',
        type: 'n_back',
        description: 'N-back task at n=1, below current level',
        parameters: { n: 1, trials: 6, stimulusDurationMs: 1100, interStimulusMs: 350 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to foundations without shame',
      addictionSignal: 'Refuses below-level engagement',
      allergySignal: 'Compartmentalises, cannot embody in reality',
    },
  },
};
