import type { AssessmentItem, StageAssessment } from '../types.js';

export const interpersonalInfrared: StageAssessment = {
  line: 'Interpersonal',
  stage: 'Infrared',
  tasks: [
    {
      id: 'inter-ir-imitate',
      type: 'imitation',
      description: 'Pre-other minimal: imitate simple NPC action',
      parameters: { actionType: 'single-tap', demonstrations: 3, trials: 4 },
      measures: ['accuracy', 'response_time'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.4,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      transfer: 0.2,
      depth: 0.3,
    },
  },
  minimumTrials: 2,
  estimatedDurationMs: 60000,
  itemPool: [
    { id: 'interpersonal-infrared-01', taskType: 'imitation', difficulty: 0.2, parameters: { actionType: 'single-tap', demonstrations: 3, trials: 2 }, measures: ['accuracy'] },
    { id: 'interpersonal-infrared-02', taskType: 'imitation', difficulty: 0.25, parameters: { actionType: 'single-tap', demonstrations: 3, trials: 3 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-03', taskType: 'imitation', difficulty: 0.3, parameters: { actionType: 'single-tap', demonstrations: 2, trials: 3 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-04', taskType: 'imitation', difficulty: 0.35, parameters: { actionType: 'single-tap', demonstrations: 2, trials: 4, mirrorMode: true }, measures: ['accuracy'] },
    { id: 'interpersonal-infrared-05', taskType: 'imitation', difficulty: 0.4, parameters: { actionType: 'single-tap', demonstrations: 2, trials: 4, approachAvoid: true }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-06', taskType: 'imitation', difficulty: 0.4, parameters: { actionType: 'double-tap', demonstrations: 3, trials: 3 }, measures: ['accuracy'] },
    { id: 'interpersonal-infrared-07', taskType: 'imitation', difficulty: 0.45, parameters: { actionType: 'double-tap', demonstrations: 3, trials: 4, mirrorMode: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-infrared-08', taskType: 'imitation', difficulty: 0.5, parameters: { actionType: 'single-tap', demonstrations: 2, trials: 5, turnTaking: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-infrared-09', taskType: 'imitation', difficulty: 0.5, parameters: { actionType: 'double-tap', demonstrations: 2, trials: 4 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-10', taskType: 'imitation', difficulty: 0.55, parameters: { actionType: 'single-tap', demonstrations: 1, trials: 5, mirrorMode: true }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-11', taskType: 'imitation', difficulty: 0.55, parameters: { actionType: 'double-tap', demonstrations: 2, trials: 5, turnTaking: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-infrared-12', taskType: 'imitation', difficulty: 0.6, parameters: { actionType: 'two-step', demonstrations: 3, trials: 3 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-13', taskType: 'imitation', difficulty: 0.6, parameters: { actionType: 'single-tap', demonstrations: 1, trials: 6, approachAvoid: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-infrared-14', taskType: 'imitation', difficulty: 0.65, parameters: { actionType: 'two-step', demonstrations: 2, trials: 4 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-15', taskType: 'imitation', difficulty: 0.7, parameters: { actionType: 'two-step', demonstrations: 2, trials: 4, mirrorMode: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-infrared-16', taskType: 'imitation', difficulty: 0.7, parameters: { actionType: 'two-step', demonstrations: 2, trials: 5, turnTaking: true }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'interpersonal-infrared-17', taskType: 'imitation', difficulty: 0.75, parameters: { actionType: 'two-step', demonstrations: 1, trials: 5 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-infrared-18', taskType: 'imitation', difficulty: 0.8, parameters: { actionType: 'two-step', demonstrations: 1, trials: 6, mirrorMode: true }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'interpersonal-infrared-19', taskType: 'imitation', difficulty: 0.85, parameters: { actionType: 'two-step', demonstrations: 1, trials: 6, turnTaking: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-infrared-20', taskType: 'imitation', difficulty: 0.9, parameters: { actionType: 'two-step', demonstrations: 1, trials: 8, turnTaking: true, mirrorMode: true }, measures: ['accuracy', 'response_time', 'consistency'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Imitate without waiting for signal',
      task: {
        id: 'inter-ir-probe-agency',
        type: 'imitation',
        description: 'Imitate NPC action without waiting for go signal',
        parameters: { actionType: 'single-tap', demonstrations: 2, trials: 3, signalEnabled: false },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Initiates imitation with basic agency',
      addictionSignal: 'Acts before observing',
      allergySignal: 'Cannot initiate imitation without explicit signal',
    },
    communion: {
      description: 'Take turns imitating with NPC',
      task: {
        id: 'inter-ir-probe-communion',
        type: 'imitation',
        description: 'Take turns imitating with NPC partner',
        parameters: { actionType: 'single-tap', demonstrations: 2, trials: 3, turnTaking: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Alternates with other with basic awareness',
      addictionSignal: 'Only copies, never leads',
      allergySignal: 'Cannot attend to others actions',
    },
    eros: {
      description: 'Attempt to imitate more complex action',
      task: {
        id: 'inter-ir-probe-eros',
        type: 'imitation',
        description: 'Attempt to imitate a two-step action',
        parameters: { actionType: 'two-step', demonstrations: 3, trials: 3 },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Reaches toward more complex imitation',
      addictionSignal: 'Overwhelmed but cannot stop trying',
      allergySignal: 'Refuses to attempt complex imitation',
    },
    agape: {
      description: 'Return to simplest imitation with presence',
      task: {
        id: 'inter-ir-probe-agape',
        type: 'imitation',
        description: 'Return to simplest single-tap imitation',
        parameters: { actionType: 'single-tap', demonstrations: 3, trials: 2 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple imitation with full attention',
      addictionSignal: 'Refuses simple imitation as too easy',
      allergySignal: 'Cannot engage with other at all',
    },
  },
};
