import type { AssessmentItem, StageAssessment } from '../types.js';

export const interpersonalMagenta: StageAssessment = {
  line: 'Interpersonal',
  stage: 'Magenta',
  tasks: [
    {
      id: 'inter-mag-imitate',
      type: 'imitation',
      description: 'Simple imitation: NPC does action, you copy',
      parameters: { actionType: 'gesture-sequence', demonstrations: 3, trials: 6, sequenceLength: 2 },
      measures: ['accuracy', 'response_time'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.5,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      transfer: 0.2,
      depth: 0.3,
    },
  },
  minimumTrials: 3,
  estimatedDurationMs: 90000,
  itemPool: [
    { id: 'interpersonal-magenta-01', taskType: 'imitation', difficulty: 0.2, parameters: { actionType: 'single-tap', demonstrations: 3, trials: 3, sequenceLength: 1 }, measures: ['accuracy'] },
    { id: 'interpersonal-magenta-02', taskType: 'imitation', difficulty: 0.25, parameters: { actionType: 'single-tap', demonstrations: 3, trials: 4, sequenceLength: 1 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-03', taskType: 'imitation', difficulty: 0.3, parameters: { actionType: 'gesture-sequence', demonstrations: 3, trials: 4, sequenceLength: 2 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-04', taskType: 'imitation', difficulty: 0.35, parameters: { actionType: 'gesture-sequence', demonstrations: 3, trials: 5, sequenceLength: 2 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-05', taskType: 'imitation', difficulty: 0.4, parameters: { actionType: 'gesture-sequence', demonstrations: 3, trials: 6, sequenceLength: 2 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-06', taskType: 'cooperation', difficulty: 0.3, parameters: { taskType: 'parallel-play', partners: 1, rounds: 3 }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-magenta-07', taskType: 'cooperation', difficulty: 0.35, parameters: { taskType: 'parallel-play', partners: 1, rounds: 4 }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-magenta-08', taskType: 'imitation', difficulty: 0.45, parameters: { actionType: 'gesture-sequence', demonstrations: 2, trials: 5, sequenceLength: 2 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-09', taskType: 'cooperation', difficulty: 0.4, parameters: { taskType: 'simple-turn-taking', partners: 1, rounds: 4 }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-magenta-10', taskType: 'imitation', difficulty: 0.5, parameters: { actionType: 'gesture-sequence', demonstrations: 2, trials: 6, sequenceLength: 2, turnTaking: true }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-magenta-11', taskType: 'cooperation', difficulty: 0.5, parameters: { taskType: 'simple-turn-taking', partners: 1, rounds: 5 }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-magenta-12', taskType: 'imitation', difficulty: 0.55, parameters: { actionType: 'gesture-sequence', demonstrations: 2, trials: 5, sequenceLength: 3 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-13', taskType: 'cooperation', difficulty: 0.6, parameters: { taskType: 'basic-cooperation', partners: 1, rounds: 4 }, measures: ['accuracy', 'consistency', 'transfer'] },
    { id: 'interpersonal-magenta-14', taskType: 'imitation', difficulty: 0.6, parameters: { actionType: 'gesture-sequence', demonstrations: 2, trials: 6, sequenceLength: 3 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-15', taskType: 'imitation', difficulty: 0.65, parameters: { actionType: 'gesture-sequence', demonstrations: 1, trials: 5, sequenceLength: 3 }, measures: ['accuracy', 'response_time'] },
    { id: 'interpersonal-magenta-16', taskType: 'cooperation', difficulty: 0.7, parameters: { taskType: 'basic-cooperation', partners: 1, rounds: 5 }, measures: ['accuracy', 'consistency', 'transfer'] },
    { id: 'interpersonal-magenta-17', taskType: 'imitation', difficulty: 0.75, parameters: { actionType: 'gesture-sequence', demonstrations: 1, trials: 5, sequenceLength: 3, turnTaking: true }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'interpersonal-magenta-18', taskType: 'cooperation', difficulty: 0.8, parameters: { taskType: 'coordinated-action', partners: 1, rounds: 5 }, measures: ['accuracy', 'consistency', 'transfer'] },
    { id: 'interpersonal-magenta-19', taskType: 'imitation', difficulty: 0.85, parameters: { actionType: 'gesture-sequence', demonstrations: 1, trials: 6, sequenceLength: 4 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'interpersonal-magenta-20', taskType: 'imitation', difficulty: 0.9, parameters: { actionType: 'gesture-sequence', demonstrations: 1, trials: 6, sequenceLength: 4, turnTaking: true }, measures: ['accuracy', 'response_time', 'consistency', 'transfer'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Imitate after single demonstration',
      task: {
        id: 'inter-mag-probe-agency',
        type: 'imitation',
        description: 'Copy NPC action after just one demonstration',
        parameters: { actionType: 'gesture-sequence', demonstrations: 1, trials: 3, sequenceLength: 2 },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Imitates with confidence after single view',
      addictionSignal: 'Acts before fully observing',
      allergySignal: 'Needs many repetitions before attempting',
    },
    communion: {
      description: 'Take turns: NPC imitates you, then you imitate NPC',
      task: {
        id: 'inter-mag-probe-communion',
        type: 'imitation',
        description: 'Reciprocal imitation with NPC partner',
        parameters: { actionType: 'gesture-sequence', demonstrations: 2, trials: 4, turnTaking: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Alternates roles with engagement',
      addictionSignal: 'Only wants to be copied, not to copy',
      allergySignal: 'Only copies, cannot lead',
    },
    eros: {
      description: 'Attempt to imitate a 3-step sequence',
      task: {
        id: 'inter-mag-probe-eros',
        type: 'imitation',
        description: 'Imitate longer three-step sequence',
        parameters: { actionType: 'gesture-sequence', demonstrations: 2, trials: 3, sequenceLength: 3 },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Reaches toward longer sequence with effort',
      addictionSignal: 'Overwhelmed but cannot stop trying',
      allergySignal: 'Refuses longer sequences',
    },
    agape: {
      description: 'Return to single-action imitation with care',
      task: {
        id: 'inter-mag-probe-agape',
        type: 'imitation',
        description: 'Return to simple single-action imitation',
        parameters: { actionType: 'single-tap', demonstrations: 3, trials: 3 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple imitation with full attention',
      addictionSignal: 'Refuses simple action as too easy',
      allergySignal: 'Cannot engage with imitation at all',
    },
  },
};
