import type { AssessmentItem, StageAssessment } from '../types.js';

export const willpowerInfrared: StageAssessment = {
  line: 'Willpower',
  stage: 'Infrared',
  tasks: [
    {
      id: 'will-ir-brief-hold',
      type: 'hold',
      description: 'Pre-volitional: very brief hold (1 second)',
      parameters: { targetDurationMs: 1000, perturbations: false },
      measures: ['accuracy', 'consistency'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.4,
    dimensionWeights: {
      consistency: 0.3,
      complexity_handled: 0.3,
      transfer: 0.2,
      response_time: 0.2,
    },
  },
  minimumTrials: 2,
  estimatedDurationMs: 45000,
  itemPool: [
    { id: 'willpower-infrared-01', taskType: 'hold', difficulty: 0.2, parameters: { targetDurationMs: 500, perturbations: false }, measures: ['accuracy'] },
    { id: 'willpower-infrared-02', taskType: 'hold', difficulty: 0.25, parameters: { targetDurationMs: 700, perturbations: false }, measures: ['accuracy'] },
    { id: 'willpower-infrared-03', taskType: 'hold', difficulty: 0.3, parameters: { targetDurationMs: 1000, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-04', taskType: 'go_no_go', difficulty: 0.3, parameters: { goRatio: 0.8, trials: 6, stimulusDurationMs: 1500 }, measures: ['accuracy'] },
    { id: 'willpower-infrared-05', taskType: 'hold', difficulty: 0.35, parameters: { targetDurationMs: 1200, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-06', taskType: 'go_no_go', difficulty: 0.35, parameters: { goRatio: 0.8, trials: 8, stimulusDurationMs: 1400 }, measures: ['accuracy', 'response_time'] },
    { id: 'willpower-infrared-07', taskType: 'hold', difficulty: 0.4, parameters: { targetDurationMs: 1500, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-08', taskType: 'go_no_go', difficulty: 0.4, parameters: { goRatio: 0.75, trials: 8, stimulusDurationMs: 1300 }, measures: ['accuracy', 'response_time'] },
    { id: 'willpower-infrared-09', taskType: 'hold', difficulty: 0.45, parameters: { targetDurationMs: 1800, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-10', taskType: 'go_no_go', difficulty: 0.5, parameters: { goRatio: 0.75, trials: 10, stimulusDurationMs: 1200 }, measures: ['accuracy', 'response_time'] },
    { id: 'willpower-infrared-11', taskType: 'hold', difficulty: 0.5, parameters: { targetDurationMs: 2000, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-12', taskType: 'go_no_go', difficulty: 0.55, parameters: { goRatio: 0.7, trials: 10, stimulusDurationMs: 1100 }, measures: ['accuracy', 'response_time'] },
    { id: 'willpower-infrared-13', taskType: 'hold', difficulty: 0.6, parameters: { targetDurationMs: 2500, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-14', taskType: 'go_no_go', difficulty: 0.6, parameters: { goRatio: 0.7, trials: 12, stimulusDurationMs: 1000 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'willpower-infrared-15', taskType: 'hold', difficulty: 0.65, parameters: { targetDurationMs: 3000, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-16', taskType: 'go_no_go', difficulty: 0.7, parameters: { goRatio: 0.65, trials: 12, stimulusDurationMs: 900 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'willpower-infrared-17', taskType: 'hold', difficulty: 0.75, parameters: { targetDurationMs: 3500, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-18', taskType: 'hold', difficulty: 0.8, parameters: { targetDurationMs: 4000, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-infrared-19', taskType: 'go_no_go', difficulty: 0.85, parameters: { goRatio: 0.6, trials: 14, stimulusDurationMs: 800 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'willpower-infrared-20', taskType: 'hold', difficulty: 0.9, parameters: { targetDurationMs: 5000, perturbations: false }, measures: ['accuracy', 'consistency'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Hold briefly without countdown',
      task: {
        id: 'will-ir-probe-agency',
        type: 'hold',
        description: 'Brief hold without external countdown',
        parameters: { targetDurationMs: 1000, perturbations: false, countdownEnabled: false },
        measures: ['accuracy'],
      },
      healthyResponse: 'Holds briefly with basic volition',
      addictionSignal: 'Holds beyond required, cannot release',
      allergySignal: 'Cannot sustain even momentary hold',
    },
    communion: {
      description: 'Hold alongside NPC partner',
      task: {
        id: 'will-ir-probe-communion',
        type: 'hold',
        description: 'Brief hold alongside NPC partner',
        parameters: { targetDurationMs: 1000, perturbations: false, partnerMode: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Holds alongside other with basic awareness',
      addictionSignal: 'Loses own timing to match partner',
      allergySignal: 'Cannot hold with awareness of other',
    },
    eros: {
      description: 'Attempt slightly longer hold (2 seconds)',
      task: {
        id: 'will-ir-probe-eros',
        type: 'hold',
        description: 'Attempt slightly longer hold than baseline',
        parameters: { targetDurationMs: 2000, perturbations: false },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Reaches toward longer hold with willingness',
      addictionSignal: 'Compulsively extends beyond capacity',
      allergySignal: 'Refuses any extension',
    },
    agape: {
      description: 'Very brief hold with full presence',
      task: {
        id: 'will-ir-probe-agape',
        type: 'hold',
        description: 'Momentary hold with full awareness',
        parameters: { targetDurationMs: 500, perturbations: false },
        measures: ['accuracy'],
      },
      healthyResponse: 'Holds briefly with full presence',
      addictionSignal: 'Refuses brief hold as too easy',
      allergySignal: 'Cannot engage will at all',
    },
  },
};
