import type { AssessmentItem, StageAssessment } from '../types.js';

export const somaticRed: StageAssessment = {
  line: 'Somatic',
  stage: 'Red',
  tasks: [
    {
      id: 'som-red-fast-rt',
      type: 'reaction_time',
      description: 'Fast reaction time: tap when stimulus appears',
      parameters: { stimulusType: 'simple', targetCount: 10, minGap: 500, maxGap: 2000 },
      measures: ['response_time', 'accuracy'],
    },
    {
      id: 'som-red-alternation',
      type: 'reaction_time',
      description: 'Rapid alternation: left-right-left-right tapping',
      parameters: { stimulusType: 'alternation', targetCount: 16, paceMs: 600 },
      measures: ['response_time', 'accuracy', 'consistency'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.6,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.3,
      consistency: 0.4,
    },
  },
  minimumTrials: 4,
  estimatedDurationMs: 120000,
  itemPool: [
    { id: 'somatic-red-01', taskType: 'reaction_time', difficulty: 0.2, parameters: { stimulusType: 'simple', targetCount: 6, minGap: 800, maxGap: 2500 }, measures: ['response_time', 'accuracy'] },
    { id: 'somatic-red-02', taskType: 'reaction_time', difficulty: 0.25, parameters: { stimulusType: 'simple', targetCount: 8, minGap: 700, maxGap: 2200 }, measures: ['response_time', 'accuracy'] },
    { id: 'somatic-red-03', taskType: 'rhythm', difficulty: 0.3, parameters: { bpm: 60, beats: 8, pattern: 'steady' }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-04', taskType: 'reaction_time', difficulty: 0.3, parameters: { stimulusType: 'simple', targetCount: 10, minGap: 600, maxGap: 2000 }, measures: ['response_time', 'accuracy', 'consistency'] },
    { id: 'somatic-red-05', taskType: 'rhythm', difficulty: 0.35, parameters: { bpm: 80, beats: 10, pattern: 'steady' }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-06', taskType: 'reaction_time', difficulty: 0.4, parameters: { stimulusType: 'alternation', targetCount: 10, paceMs: 700 }, measures: ['response_time', 'accuracy', 'consistency'] },
    { id: 'somatic-red-07', taskType: 'hold', difficulty: 0.4, parameters: { targetDurationMs: 2000, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-08', taskType: 'rhythm', difficulty: 0.45, parameters: { bpm: 90, beats: 12, pattern: 'alternating' }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-09', taskType: 'reaction_time', difficulty: 0.5, parameters: { stimulusType: 'alternation', targetCount: 14, paceMs: 600 }, measures: ['response_time', 'accuracy', 'consistency'] },
    { id: 'somatic-red-10', taskType: 'hold', difficulty: 0.5, parameters: { targetDurationMs: 3000, perturbations: false }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-11', taskType: 'rhythm', difficulty: 0.55, parameters: { bpm: 100, beats: 14, pattern: 'syncopated' }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-12', taskType: 'reaction_time', difficulty: 0.6, parameters: { stimulusType: 'alternation', targetCount: 16, paceMs: 550 }, measures: ['response_time', 'accuracy', 'consistency'] },
    { id: 'somatic-red-13', taskType: 'hold', difficulty: 0.6, parameters: { targetDurationMs: 3500, perturbations: true, perturbationIntervalMs: 1200 }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-14', taskType: 'rhythm', difficulty: 0.65, parameters: { bpm: 110, beats: 16, pattern: 'syncopated' }, measures: ['accuracy', 'consistency', 'response_time'] },
    { id: 'somatic-red-15', taskType: 'reaction_time', difficulty: 0.7, parameters: { stimulusType: 'alternation', targetCount: 18, paceMs: 500 }, measures: ['response_time', 'accuracy', 'consistency'] },
    { id: 'somatic-red-16', taskType: 'hold', difficulty: 0.7, parameters: { targetDurationMs: 4000, perturbations: true, perturbationIntervalMs: 1000 }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-red-17', taskType: 'rhythm', difficulty: 0.75, parameters: { bpm: 120, beats: 16, pattern: 'complex' }, measures: ['accuracy', 'consistency', 'response_time'] },
    { id: 'somatic-red-18', taskType: 'reaction_time', difficulty: 0.8, parameters: { stimulusType: 'alternation', targetCount: 20, paceMs: 450 }, measures: ['response_time', 'accuracy', 'consistency'] },
    { id: 'somatic-red-19', taskType: 'rhythm', difficulty: 0.85, parameters: { bpm: 130, beats: 20, pattern: 'complex' }, measures: ['accuracy', 'consistency', 'response_time'] },
    { id: 'somatic-red-20', taskType: 'reaction_time', difficulty: 0.9, parameters: { stimulusType: 'alternation', targetCount: 24, paceMs: 400 }, measures: ['response_time', 'accuracy', 'consistency'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Respond without encouragement or external timing cues',
      task: {
        id: 'som-red-probe-agency',
        type: 'reaction_time',
        description: 'React to stimuli without external encouragement or timing',
        parameters: { stimulusType: 'simple', targetCount: 6, minGap: 500, maxGap: 2000, cuesEnabled: false },
        measures: ['response_time', 'accuracy'],
      },
      healthyResponse: 'Responds with self-generated timing and initiative',
      addictionSignal: 'Responds aggressively, cannot modulate pace',
      allergySignal: 'Cannot initiate without external cue',
    },
    communion: {
      description: 'Sync your tapping rhythm with an NPC partner',
      task: {
        id: 'som-red-probe-communion',
        type: 'reaction_time',
        description: 'Synchronize tapping rhythm with NPC partner',
        parameters: { stimulusType: 'sync', targetCount: 8, paceMs: 700, partnerMode: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Coordinates with other while maintaining own rhythm',
      addictionSignal: 'Loses own rhythm entirely to match other',
      allergySignal: 'Refuses to adjust timing to coordinate',
    },
    eros: {
      description: 'Attempt faster pace than current comfort',
      task: {
        id: 'som-red-probe-eros',
        type: 'reaction_time',
        description: 'Attempt faster-than-comfortable tapping pace',
        parameters: { stimulusType: 'alternation', targetCount: 12, paceMs: 400 },
        measures: ['response_time', 'accuracy'],
      },
      healthyResponse: 'Reaches toward speed with curiosity and effort',
      addictionSignal: 'Compulsively pushes speed, cannot slow down',
      allergySignal: 'Refuses to attempt faster pace, treats edge as dangerous',
    },
    agape: {
      description: 'Do slow, easy tapping with full presence and care',
      task: {
        id: 'som-red-probe-agape',
        type: 'reaction_time',
        description: 'Slow easy tapping with full somatic presence',
        parameters: { stimulusType: 'simple', targetCount: 6, minGap: 1500, maxGap: 3000 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Engages fully with simple movement without boredom',
      addictionSignal: 'Refuses easy pace as too slow',
      allergySignal: 'Cannot engage with body even at easy level',
    },
  },
};
