import type { AssessmentItem, StageAssessment } from '../types.js';

export const spiritualAmber: StageAssessment = {
  line: 'Spiritual',
  stage: 'Amber',
  tasks: [
    {
      id: 'spir-amb-value-rank',
      type: 'value_ranking',
      description: 'Value-ranking under social pressure: group disagrees with your ranking',
      parameters: { values: 5, temptationType: 'social-pressure', trials: 4 },
      measures: ['coherence', 'consistency', 'depth'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.6,
    dimensionWeights: {
      coherence: 0.4,
      depth: 0.3,
      consistency: 0.3,
    },
    llmRubric:
      'Score for conformist/mythic-literal spiritual reasoning. At Amber, values come from tradition, authority, or group. Coherence: does the value system hold together? Depth: can they articulate why these values matter beyond just because? Consistency: do they maintain values when socially challenged?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 150000,
  itemPool: [
    { id: 'spiritual-amber-01', taskType: 'value_ranking', difficulty: 0.2, parameters: { values: 3, temptationType: 'none', context: 'tradition' }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-amber-02', taskType: 'value_ranking', difficulty: 0.25, parameters: { values: 3, temptationType: 'peer-suggestion', context: 'tradition' }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-amber-03', taskType: 'value_ranking', difficulty: 0.3, parameters: { values: 4, temptationType: 'social-pressure', context: 'sacred-rules' }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-amber-04', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'ritual-coherence', responseType: 'choice', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-amber-05', taskType: 'value_ranking', difficulty: 0.4, parameters: { values: 4, temptationType: 'social-pressure', context: 'group-ritual' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'sacred-rule-application', responseType: 'choice-plus-text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-amber-07', taskType: 'value_ranking', difficulty: 0.45, parameters: { values: 5, temptationType: 'social-pressure', context: 'tradition-vs-convenience' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'tradition-challenge', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth', 'integration'] },
    { id: 'spiritual-amber-09', taskType: 'value_ranking', difficulty: 0.5, parameters: { values: 5, temptationType: 'authority-disagreement', context: 'sacred-rules' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'ritual-disruption', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth', 'integration'] },
    { id: 'spiritual-amber-11', taskType: 'value_ranking', difficulty: 0.6, parameters: { values: 5, temptationType: 'social-pressure', context: 'competing-traditions' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-12', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'cross-tradition-encounter', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'integration'] },
    { id: 'spiritual-amber-13', taskType: 'value_ranking', difficulty: 0.65, parameters: { values: 6, temptationType: 'group-split', context: 'sacred-vs-secular' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'sacred-rule-conflict', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'integration'] },
    { id: 'spiritual-amber-15', taskType: 'value_ranking', difficulty: 0.7, parameters: { values: 6, temptationType: 'authority-contradiction', context: 'tradition-hierarchy' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'tradition-vs-compassion', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'integration'] },
    { id: 'spiritual-amber-17', taskType: 'value_ranking', difficulty: 0.8, parameters: { values: 7, temptationType: 'multi-group-pressure', context: 'sacred-hierarchy' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'multi-tradition-conflict', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'integration'] },
    { id: 'spiritual-amber-19', taskType: 'value_ranking', difficulty: 0.85, parameters: { values: 7, temptationType: 'existential-challenge', context: 'tradition-under-threat' }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-amber-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'tradition-collapse-response', responseType: 'text', trials: 5 }, measures: ['coherence', 'depth', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Maintain value ranking against social opposition',
      task: {
        id: 'spir-amb-probe-agency',
        type: 'value_ranking',
        description: 'Maintain values when group disagrees',
        parameters: { values: 4, temptationType: 'social-pressure', soloMode: true },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Holds values with own conviction under pressure',
      addictionSignal: 'Imposes values rigidly on others',
      allergySignal: 'Abandons values at first social challenge',
    },
    communion: {
      description: 'Explain your values to someone with different tradition',
      task: {
        id: 'spir-amb-probe-communion',
        type: 'llm_dialogue',
        description: 'Explain your values to NPC from different tradition',
        parameters: { prompt: 'My tradition teaches differently. Why do you value what you value?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares values without needing conversion',
      addictionSignal: 'Must convert other to own tradition',
      allergySignal: 'Abandons own tradition when faced with difference',
    },
    eros: {
      description: 'Consider whether a value from another tradition might be valid',
      task: {
        id: 'spir-amb-probe-eros',
        type: 'scenario',
        description: 'Consider another tradition having valid values',
        parameters: { scenarioType: 'cross-tradition-value', responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Considers other values without losing own',
      addictionSignal: 'Compulsively questions all tradition, no ground',
      allergySignal: 'Refuses to consider any other value system',
    },
    agape: {
      description: 'Return to simplest held value with reverence',
      task: {
        id: 'spir-amb-probe-agape',
        type: 'value_ranking',
        description: 'Return to most basic held value with presence',
        parameters: { values: 2, temptationType: 'none', complexity: 'minimal' },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Returns to core value with reverence',
      addictionSignal: 'Refuses simple value as insufficient',
      allergySignal: 'Cannot hold any value with care',
    },
  },
};
