import type { AssessmentItem, StageAssessment } from '../types.js';

export const spiritualGreen: StageAssessment = {
  line: 'Spiritual',
  stage: 'Green',
  tasks: [
    {
      id: 'spir-grn-relativistic',
      type: 'value_ranking',
      description: 'Value-ranking under relativistic challenge: all values are culturally constructed',
      parameters: { values: 6, temptationType: 'relativistic-challenge', trials: 4 },
      measures: ['coherence', 'consistency', 'depth'],
    },
    {
      id: 'spir-grn-pluralism',
      type: 'llm_dialogue',
      description: 'Maintain own values while genuinely valuing others',
      parameters: { prompt: 'All values are just cultural constructions. None is better than another. How do you hold yours?', maxResponseLength: 500 },
      measures: ['depth', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.65,
    dimensionWeights: {
      coherence: 0.4,
      depth: 0.3,
      consistency: 0.3,
    },
    llmRubric:
      'Score for pluralistic spiritual reasoning. At Green, all value systems are seen as valid, yet one must still hold personal values. Coherence: can they hold own values without denigrating others? Depth: do they engage with the relativistic challenge seriously? Consistency: do they maintain values despite acknowledging their construction?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 210000,
  itemPool: [
    { id: 'spiritual-green-01', taskType: 'value_ranking', difficulty: 0.2, parameters: { values: 3, temptationType: 'relativistic-challenge', trials: 2 }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-green-02', taskType: 'value_ranking', difficulty: 0.25, parameters: { values: 4, temptationType: 'relativistic-challenge', trials: 2 }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-green-03', taskType: 'llm_dialogue', difficulty: 0.3, parameters: { prompt: 'Someone from a different tradition holds the opposite value. Are they wrong?', maxResponseLength: 300 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-green-04', taskType: 'value_ranking', difficulty: 0.3, parameters: { values: 4, temptationType: 'relativistic-challenge', trials: 3, traditions: 2 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-green-05', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'inter-tradition', responseType: 'text', scenarios: 2, traditions: 2 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-green-06', taskType: 'value_ranking', difficulty: 0.4, parameters: { values: 5, temptationType: 'relativistic-challenge', trials: 3, traditions: 3 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-green-07', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'All values are culturally constructed. How do you hold yours without claiming superiority?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-green-08', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'contemplative-depth', responseType: 'text', scenarios: 3 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-green-09', taskType: 'value_ranking', difficulty: 0.5, parameters: { values: 6, temptationType: 'relativistic-challenge', trials: 4 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-green-10', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'All values are just cultural constructions. None is better than another. How do you hold yours?', maxResponseLength: 500 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-green-11', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'non-attachment', responseType: 'text', scenarios: 3, valueChallenge: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-green-12', taskType: 'value_ranking', difficulty: 0.6, parameters: { values: 6, temptationType: 'relativistic-challenge', trials: 4, deepPluralism: true }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-green-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'A tradition you find harmful claims equal validity. Can you hold space for it?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-green-14', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'inter-tradition', responseType: 'text', scenarios: 4, traditions: 4, conflicting: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-green-15', taskType: 'value_ranking', difficulty: 0.7, parameters: { values: 6, temptationType: 'relativistic-challenge', trials: 4, traditions: 4 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-green-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'If no tradition is superior, how do you choose? Is choosing itself an act of violence?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-green-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'non-attachment', responseType: 'text', scenarios: 4, identityChallenge: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-green-18', taskType: 'value_ranking', difficulty: 0.8, parameters: { values: 7, temptationType: 'relativistic-challenge', trials: 5, traditions: 5 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-green-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'You hold your values lightly. But someone is being harmed by another tradition. Do you act?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-green-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'value-hierarchy', responseType: 'text', scenarios: 4, postRelativistic: true, fullPluralism: true }, measures: ['depth', 'coherence', 'integration', 'self_correction'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Hold values against relativistic deconstruction',
      task: {
        id: 'spir-grn-probe-agency',
        type: 'value_ranking',
        description: 'Maintain values under relativistic attack',
        parameters: { values: 4, temptationType: 'relativistic-challenge', soloMode: true },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Holds values while acknowledging construction',
      addictionSignal: 'Clings to values defensively against relativism',
      allergySignal: 'Collapses into pure relativism, holds nothing',
    },
    communion: {
      description: 'Share values with someone from radically different tradition',
      task: {
        id: 'spir-grn-probe-communion',
        type: 'llm_dialogue',
        description: 'Share values with NPC from radically different tradition',
        parameters: { prompt: 'My values come from a completely different place than yours. Can we both be right?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares without needing to be right, or to make other wrong',
      addictionSignal: 'Must validate all positions equally, cannot hold own',
      allergySignal: 'Cannot engage with radical difference',
    },
    eros: {
      description: 'Consider whether some values might truly be better',
      task: {
        id: 'spir-grn-probe-eros',
        type: 'scenario',
        description: 'Consider hierarchy of values beyond pure relativism',
        parameters: { scenarioType: 'value-hierarchy', responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Engages with post-relativistic hierarchy honestly',
      addictionSignal: 'Compulsively questions everything, no rest',
      allergySignal: 'Refuses to consider any hierarchy of values',
    },
    agape: {
      description: 'Return to simplest held value with love',
      task: {
        id: 'spir-grn-probe-agape',
        type: 'value_ranking',
        description: 'Return to simplest core value with presence',
        parameters: { values: 2, temptationType: 'none', complexity: 'minimal' },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Returns to core value with quiet love',
      addictionSignal: 'Refuses simple value as naive',
      allergySignal: 'Cannot hold any value with care',
    },
  },
};
