import type { AssessmentItem, StageAssessment } from '../types.js';

export const spiritualMagenta: StageAssessment = {
  line: 'Spiritual',
  stage: 'Magenta',
  tasks: [
    {
      id: 'spir-mag-magical',
      type: 'scenario',
      description: 'Magical faith belief structure: what happens when you wish?',
      parameters: { scenarioType: 'magical-wish', responseType: 'text', trials: 3 },
      measures: ['coherence', 'depth'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.5,
    dimensionWeights: {
      coherence: 0.4,
      depth: 0.3,
      consistency: 0.3,
    },
    llmRubric:
      'Score for magical/animistic spiritual reasoning. At Magenta, the world is enchanted - wishes come true, spirits are real, rituals work. Coherence: is their magical worldview internally consistent? Depth: how rich is their mythic imagination? Consistency: do they hold the same beliefs across questions?',
  },
  minimumTrials: 2,
  estimatedDurationMs: 90000,
  itemPool: [
    { id: 'spiritual-magenta-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'magical-wonder', responseType: 'single-word', trials: 2 }, measures: ['coherence'] },
    { id: 'spiritual-magenta-02', taskType: 'scenario', difficulty: 0.25, parameters: { scenarioType: 'magical-wonder', responseType: 'single-word', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-03', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'magical-wish', responseType: 'single-word', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-04', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'magical-wish', responseType: 'text', trials: 2 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'magical-wish', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'animistic-belief', responseType: 'choice', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'simple-ritual', responseType: 'choice-plus-text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'animistic-belief', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-09', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'magical-cause-effect', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'spirit-world', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'ritual-engagement', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-12', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'wish-failure', responseType: 'text', trials: 2 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'magical-protection', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'wish-failure', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth'] },
    { id: 'spiritual-magenta-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'enchanted-world', responseType: 'text', trials: 3 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'ritual-coherence', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'magical-worldview-consistency', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'spirit-communication', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'magical-belief-challenge', responseType: 'text', trials: 4 }, measures: ['coherence', 'depth', 'consistency'] },
    { id: 'spiritual-magenta-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'full-mythic-narrative', responseType: 'text', trials: 5 }, measures: ['coherence', 'depth', 'consistency', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'State magical belief without needing agreement',
      task: {
        id: 'spir-mag-probe-agency',
        type: 'scenario',
        description: 'State what you believe happens when you wish',
        parameters: { scenarioType: 'magical-wish', responseType: 'text', soloMode: true },
        measures: ['coherence', 'depth'],
      },
      healthyResponse: 'Holds magical belief with own conviction',
      addictionSignal: 'Imposes belief on others aggressively',
      allergySignal: 'Cannot hold any belief without permission',
    },
    communion: {
      description: 'Share magical belief with NPC',
      task: {
        id: 'spir-mag-probe-communion',
        type: 'llm_dialogue',
        description: 'Share what you believe about wishes with NPC',
        parameters: { prompt: 'Do you believe in magic? Tell me about it.', maxResponseLength: 200 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares belief without needing agreement',
      addictionSignal: 'Loses own belief to match other',
      allergySignal: 'Refuses to share inner world',
    },
    eros: {
      description: 'Consider what happens when wishes do not come true',
      task: {
        id: 'spir-mag-probe-eros',
        type: 'scenario',
        description: 'Face scenario where a wish does not come true',
        parameters: { scenarioType: 'wish-failure', responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Engages with challenge to magical thinking',
      addictionSignal: 'Compulsively questions everything',
      allergySignal: 'Refuses to acknowledge wish can fail',
    },
    agape: {
      description: 'Return to simplest magical feeling with presence',
      task: {
        id: 'spir-mag-probe-agape',
        type: 'scenario',
        description: 'Return to simple wonder and magical feeling',
        parameters: { scenarioType: 'magical-wonder', responseType: 'single-word' },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Returns to wonder with ease and openness',
      addictionSignal: 'Demands more complexity from wonder',
      allergySignal: 'Cannot engage with wonder at all',
    },
  },
};
