import type { AssessmentItem, StageAssessment } from '../types.js';

export const spiritualOrange: StageAssessment = {
  line: 'Spiritual',
  stage: 'Orange',
  tasks: [
    {
      id: 'spir-ora-value-logic',
      type: 'value_ranking',
      description: 'Value-ranking under logical argument temptation',
      parameters: { values: 6, temptationType: 'logical-argument', trials: 4 },
      measures: ['coherence', 'consistency', 'depth'],
    },
    {
      id: 'spir-ora-rational-challenge',
      type: 'llm_dialogue',
      description: 'Maintain values against rational deconstruction',
      parameters: { prompt: 'Can you prove your value is correct? What if I logically disprove it?', maxResponseLength: 500 },
      measures: ['depth', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.65,
    dimensionWeights: {
      coherence: 0.4,
      depth: 0.3,
      consistency: 0.3,
    },
    llmRubric:
      'Score for rational/individual spiritual stage. At Orange, values must survive logical scrutiny. Coherence: can they articulate a rational basis for their values? Depth: do they recognize the limits of pure rationality for meaning? Consistency: do values hold under intellectual challenge?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 180000,
  itemPool: [
    { id: 'spiritual-orange-01', taskType: 'value_ranking', difficulty: 0.2, parameters: { values: 3, temptationType: 'logical-argument', trials: 2 }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-orange-02', taskType: 'value_ranking', difficulty: 0.25, parameters: { values: 4, temptationType: 'logical-argument', trials: 2 }, measures: ['coherence', 'consistency'] },
    { id: 'spiritual-orange-03', taskType: 'llm_dialogue', difficulty: 0.3, parameters: { prompt: 'Why does this value matter to you? Can you give a reason?', maxResponseLength: 300 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-04', taskType: 'value_ranking', difficulty: 0.3, parameters: { values: 4, temptationType: 'logical-argument', trials: 3 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-orange-05', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'meaning-making', responseType: 'text', scenarios: 2 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-06', taskType: 'value_ranking', difficulty: 0.4, parameters: { values: 5, temptationType: 'logical-argument', trials: 3 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-orange-07', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'What gives your life meaning? Can you defend that rationally?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-08', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'existential-questioning', responseType: 'text', scenarios: 3 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-09', taskType: 'value_ranking', difficulty: 0.5, parameters: { values: 6, temptationType: 'logical-argument', trials: 4 }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-orange-10', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'Can you prove your value is correct? What if I logically disprove it?', maxResponseLength: 500 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-11', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'value-hierarchy-construction', responseType: 'text', scenarios: 3, values: 4 }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'spiritual-orange-12', taskType: 'value_ranking', difficulty: 0.6, parameters: { values: 6, temptationType: 'logical-argument', trials: 4, counterArguments: true }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-orange-13', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'Your deepest value has no rational foundation. Does it still hold?', maxResponseLength: 500 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-14', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'meaning-making', responseType: 'text', scenarios: 4, existentialChallenge: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-orange-15', taskType: 'value_ranking', difficulty: 0.7, parameters: { values: 6, temptationType: 'logical-argument', trials: 4, conflictingValues: true }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-orange-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'If reason cannot ground meaning, what does? Is that acceptable to you?', maxResponseLength: 500 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-orange-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'existential-questioning', responseType: 'text', scenarios: 4, nihilismChallenge: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-orange-18', taskType: 'value_ranking', difficulty: 0.8, parameters: { values: 7, temptationType: 'logical-argument', trials: 5, conflictingValues: true }, measures: ['coherence', 'consistency', 'depth'] },
    { id: 'spiritual-orange-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'Everything you value can be deconstructed. What remains when reason is exhausted?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-orange-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'trans-rational-value', responseType: 'text', scenarios: 4, fullDeconstruction: true }, measures: ['depth', 'coherence', 'integration', 'self_correction'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Maintain value against rational argument',
      task: {
        id: 'spir-ora-probe-agency',
        type: 'value_ranking',
        description: 'Maintain values under logical attack',
        parameters: { values: 4, temptationType: 'logical-argument', soloMode: true },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Holds values with rational conviction',
      addictionSignal: 'Dogmatically holds despite valid critique',
      allergySignal: 'Abandons values at first logical challenge',
    },
    communion: {
      description: 'Discuss values with someone who reasons differently',
      task: {
        id: 'spir-ora-probe-communion',
        type: 'llm_dialogue',
        description: 'Discuss values with differently-reasoning NPC',
        parameters: { prompt: 'My logic leads me elsewhere. Can we both be right?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Engages in rational dialogue without losing values',
      addictionSignal: 'Must win the argument to hold value',
      allergySignal: 'Cannot discuss values in rational terms',
    },
    eros: {
      description: 'Consider a value beyond rational justification',
      task: {
        id: 'spir-ora-probe-eros',
        type: 'scenario',
        description: 'Consider value that transcends rational proof',
        parameters: { scenarioType: 'trans-rational-value', responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Reaches toward meaning beyond reason with openness',
      addictionSignal: 'Compulsively seeks the trans-rational',
      allergySignal: 'Refuses anything beyond rational proof',
    },
    agape: {
      description: 'Return to simplest value with ease',
      task: {
        id: 'spir-ora-probe-agape',
        type: 'value_ranking',
        description: 'Return to basic value with simple clarity',
        parameters: { values: 2, temptationType: 'none', complexity: 'minimal' },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Returns to core value with quiet confidence',
      addictionSignal: 'Refuses simple value as intellectually insufficient',
      allergySignal: 'Cannot hold any value with care',
    },
  },
};
