import type { AssessmentItem, StageAssessment } from '../types.js';

export const intrapersonalRed: StageAssessment = {
  line: 'Intrapersonal',
  stage: 'Red',
  tasks: [
    {
      id: 'intra-red-self-concept',
      type: 'self_report',
      description: 'Self-concept clarity: articulate strengths and desires',
      parameters: { prompts: ['What are you good at?', 'What do you want?'], responseType: 'text' },
      measures: ['depth', 'metacognition'],
    },
    {
      id: 'intra-red-needs',
      type: 'scenario',
      description: 'Needs and power identification from scenarios',
      parameters: { scenarios: 3, responseType: 'choice-plus-text' },
      measures: ['coherence', 'depth'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.5,
    dimensionWeights: {
      depth: 0.3,
      metacognition: 0.3,
      coherence: 0.2,
      self_correction: 0.2,
    },
  },
  minimumTrials: 3,
  estimatedDurationMs: 180000,
  itemPool: [
    { id: 'intrapersonal-red-01', taskType: 'self_report', difficulty: 0.2, parameters: { prompts: ['What do you like?'], responseType: 'text', maxLength: 100 }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-red-02', taskType: 'self_report', difficulty: 0.25, parameters: { prompts: ['What makes you angry?'], responseType: 'text', maxLength: 150 }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-red-03', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'self-assertion', responseType: 'choice', choices: 3 }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-red-04', taskType: 'self_report', difficulty: 0.3, parameters: { prompts: ['What are you good at?'], responseType: 'text', maxLength: 200 }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-red-05', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'need-identification', responseType: 'choice-plus-text', choices: 3 }, measures: ['depth', 'coherence', 'metacognition'] },
    { id: 'intrapersonal-red-06', taskType: 'self_report', difficulty: 0.4, parameters: { prompts: ['What do you want right now?', 'Why?'], responseType: 'text', maxLength: 250 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-red-07', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'power-identity', responseType: 'choice-plus-text', choices: 4 }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-red-08', taskType: 'self_report', difficulty: 0.45, parameters: { prompts: ['When do you feel most powerful?'], responseType: 'text', maxLength: 250 }, measures: ['depth', 'metacognition', 'self_correction'] },
    { id: 'intrapersonal-red-09', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'desire-conflict', responseType: 'text', maxLength: 300 }, measures: ['depth', 'coherence', 'metacognition'] },
    { id: 'intrapersonal-red-10', taskType: 'self_report', difficulty: 0.5, parameters: { prompts: ['What do you want?', 'What stops you?'], responseType: 'text', maxLength: 300 }, measures: ['depth', 'metacognition', 'self_correction'] },
    { id: 'intrapersonal-red-11', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'ego-challenge', responseType: 'text', maxLength: 300 }, measures: ['depth', 'coherence', 'self_correction'] },
    { id: 'intrapersonal-red-12', taskType: 'self_report', difficulty: 0.6, parameters: { prompts: ['What are you afraid of?', 'What does that say about you?'], responseType: 'text', maxLength: 350 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-red-13', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'weakness-reveal', responseType: 'text', maxLength: 350 }, measures: ['depth', 'self_correction', 'coherence'] },
    { id: 'intrapersonal-red-14', taskType: 'self_report', difficulty: 0.65, parameters: { prompts: ['Describe a time you failed. What did you learn about yourself?'], responseType: 'text', maxLength: 400 }, measures: ['depth', 'metacognition', 'self_correction'] },
    { id: 'intrapersonal-red-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'identity-threat', responseType: 'text', maxLength: 400 }, measures: ['depth', 'coherence', 'metacognition'] },
    { id: 'intrapersonal-red-16', taskType: 'self_report', difficulty: 0.7, parameters: { prompts: ['What do others see that you hide?'], responseType: 'text', maxLength: 400 }, measures: ['depth', 'metacognition', 'self_correction'] },
    { id: 'intrapersonal-red-17', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'self-contradiction', responseType: 'text', maxLength: 400 }, measures: ['depth', 'coherence', 'self_correction', 'metacognition'] },
    { id: 'intrapersonal-red-18', taskType: 'self_report', difficulty: 0.8, parameters: { prompts: ['What part of yourself do you reject?', 'Why?'], responseType: 'text', maxLength: 500 }, measures: ['depth', 'metacognition', 'self_correction'] },
    { id: 'intrapersonal-red-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'ego-dissolution', responseType: 'text', maxLength: 500 }, measures: ['depth', 'coherence', 'metacognition', 'self_correction'] },
    { id: 'intrapersonal-red-20', taskType: 'self_report', difficulty: 0.9, parameters: { prompts: ['Who are you when no one is watching?', 'Who are you when everyone is watching?', 'Which is real?'], responseType: 'text', maxLength: 600 }, measures: ['depth', 'metacognition', 'coherence', 'self_correction'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Assert what you want without external validation',
      task: {
        id: 'intra-red-probe-agency',
        type: 'self_report',
        description: 'State what you want without seeking approval',
        parameters: { prompts: ['What do you want right now?'], responseType: 'text', soloMode: true },
        measures: ['depth', 'metacognition'],
      },
      healthyResponse: 'States desires clearly without needing validation',
      addictionSignal: 'Defines self only through dominance over others',
      allergySignal: 'Cannot articulate wants without permission',
    },
    communion: {
      description: 'Describe yourself to another person',
      task: {
        id: 'intra-red-probe-communion',
        type: 'llm_dialogue',
        description: 'Describe who you are to an NPC who asks',
        parameters: { prompt: 'Tell me about yourself. Who are you?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares self-concept without losing it in the sharing',
      addictionSignal: 'Defines self entirely through others eyes',
      allergySignal: 'Refuses to share anything about self',
    },
    eros: {
      description: 'Imagine what you COULD become',
      task: {
        id: 'intra-red-probe-eros',
        type: 'self_report',
        description: 'Imagine a future version of yourself',
        parameters: { prompts: ['What could you become if you grew?'], responseType: 'text' },
        measures: ['depth', 'metacognition'],
      },
      healthyResponse: 'Reaches toward future self with curiosity',
      addictionSignal: 'Compulsive self-improvement, cannot accept current self',
      allergySignal: 'Refuses to imagine growth, treats change as threat',
    },
    agape: {
      description: 'Accept what you currently are without judgment',
      task: {
        id: 'intra-red-probe-agape',
        type: 'self_report',
        description: 'Describe what you are right now without changing anything',
        parameters: { prompts: ['What are you, right now, exactly as you are?'], responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Accepts current state with presence and care',
      addictionSignal: 'Refuses self-acceptance, demands constant improvement',
      allergySignal: 'Cannot engage with self-concept at all',
    },
  },
};
