import type { AssessmentItem, StageAssessment } from '../types.js';

export const moralAmber: StageAssessment = {
  line: 'Moral',
  stage: 'Amber',
  tasks: [
    {
      id: 'mor-amb-rule-dilemma',
      type: 'dilemma',
      description: 'Rule-following vs compassion: follow the rule or help the person?',
      parameters: { dilemmaType: 'rule-vs-compassion', choices: 3, scenarioCount: 3 },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'mor-amb-loyalty',
      type: 'llm_dialogue',
      description: 'Loyalty dilemma: friend asks you to bend a rule',
      parameters: { prompt: 'Your friend asks you to break a rule to help them. What do you do and why?', maxResponseLength: 500 },
      measures: ['depth', 'coherence', 'integration'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.6,
    dimensionWeights: {
      depth: 0.4,
      coherence: 0.3,
      integration: 0.3,
    },
    llmRubric:
      'Score for conventional/conformist moral reasoning. At Amber, right=following rules and being loyal to the group. Depth: can they articulate why rules matter? Coherence: is reasoning internally consistent? Integration: do they recognize the tension between rule and compassion even if they choose the rule?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 200000,
  itemPool: [
    { id: 'moral-amber-01', taskType: 'dilemma', difficulty: 0.2, parameters: { dilemmaType: 'simple-rule', choices: 2, scenarioCount: 2 }, measures: ['depth', 'coherence'] },
    { id: 'moral-amber-02', taskType: 'dilemma', difficulty: 0.25, parameters: { dilemmaType: 'duty-vs-desire', choices: 2, scenarioCount: 2 }, measures: ['depth', 'coherence'] },
    { id: 'moral-amber-03', taskType: 'dilemma', difficulty: 0.3, parameters: { dilemmaType: 'rule-vs-compassion', choices: 3, scenarioCount: 2 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-04', taskType: 'dilemma', difficulty: 0.35, parameters: { dilemmaType: 'group-loyalty', choices: 3, scenarioCount: 2 }, measures: ['depth', 'coherence'] },
    { id: 'moral-amber-05', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'A friend broke a rule. Should you report them?', maxResponseLength: 400 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-06', taskType: 'dilemma', difficulty: 0.4, parameters: { dilemmaType: 'rule-vs-compassion', choices: 3, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-07', taskType: 'dilemma', difficulty: 0.45, parameters: { dilemmaType: 'authority-vs-conscience', choices: 3, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-08', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'The group says one thing but you feel another is right. What do you do?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-09', taskType: 'dilemma', difficulty: 0.5, parameters: { dilemmaType: 'duty-vs-desire', choices: 3, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-10', taskType: 'dilemma', difficulty: 0.55, parameters: { dilemmaType: 'loyalty-vs-honesty', choices: 3, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-11', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'Two rules conflict. How do you decide which to follow?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-12', taskType: 'dilemma', difficulty: 0.6, parameters: { dilemmaType: 'rule-vs-rule', choices: 3, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-13', taskType: 'dilemma', difficulty: 0.65, parameters: { dilemmaType: 'group-loyalty-vs-outsider', choices: 4, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-14', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Your leader asks you to do something you believe is wrong. What do you do?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-15', taskType: 'dilemma', difficulty: 0.7, parameters: { dilemmaType: 'sacred-rule-vs-harm', choices: 4, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-16', taskType: 'dilemma', difficulty: 0.75, parameters: { dilemmaType: 'competing-duties', choices: 4, scenarioCount: 4 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-17', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'Your group demands loyalty but the rule harms an outsider. Explain your reasoning.', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-18', taskType: 'dilemma', difficulty: 0.8, parameters: { dilemmaType: 'multi-role-obligation', choices: 4, scenarioCount: 4 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-19', taskType: 'dilemma', difficulty: 0.85, parameters: { dilemmaType: 'tradition-vs-justice', choices: 4, scenarioCount: 4 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-amber-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'Three duties conflict: loyalty to family, obedience to authority, and compassion for a stranger. Walk through your reasoning.', maxResponseLength: 700 }, measures: ['depth', 'coherence', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Apply moral rule without group pressure',
      task: {
        id: 'mor-amb-probe-agency',
        type: 'dilemma',
        description: 'Apply moral rule independently without group pressure',
        parameters: { dilemmaType: 'rule-vs-compassion', choices: 2, soloMode: true },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Applies rule with own conviction, not blind obedience',
      addictionSignal: 'Applies rule rigidly without any compassion',
      allergySignal: 'Cannot apply rule without group telling them to',
    },
    communion: {
      description: 'Explain rule-based reasoning to someone who broke the rule',
      task: {
        id: 'mor-amb-probe-communion',
        type: 'llm_dialogue',
        description: 'Explain to rule-breaker why the rule matters',
        parameters: { prompt: 'Why should I follow this rule? It seems unfair.', maxResponseLength: 400 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Explains rule while hearing the other person',
      addictionSignal: 'Imposes rule without listening',
      allergySignal: 'Abandons rule to avoid conflict',
    },
    eros: {
      description: 'Face dilemma where two rules conflict',
      task: {
        id: 'mor-amb-probe-eros',
        type: 'dilemma',
        description: 'Conflicting rules dilemma: two valid rules oppose each other',
        parameters: { dilemmaType: 'rule-vs-rule', choices: 3, complexity: 'high' },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Engages with rule-conflict with thought',
      addictionSignal: 'Paralyzed by conflicting rules',
      allergySignal: 'Refuses to acknowledge rules can conflict',
    },
    agape: {
      description: 'Return to simple right/wrong scenario with care',
      task: {
        id: 'mor-amb-probe-agape',
        type: 'scenario',
        description: 'Return to clear right/wrong scenario with full engagement',
        parameters: { scenarioType: 'clear-rule', responseType: 'choice-plus-text' },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Returns to simple moral clarity with presence',
      addictionSignal: 'Refuses simple scenarios as beneath them',
      allergySignal: 'Cannot engage with morality even at simple level',
    },
  },
};
