import type { AssessmentItem, StageAssessment } from '../types.js';

export const moralOrange: StageAssessment = {
  line: 'Moral',
  stage: 'Orange',
  tasks: [
    {
      id: 'mor-ora-principle-dilemma',
      type: 'dilemma',
      description: 'Principle vs law: when law conflicts with rights',
      parameters: { dilemmaType: 'principle-vs-law', choices: 3, scenarioCount: 3 },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'mor-ora-rights-reasoning',
      type: 'llm_dialogue',
      description: 'Rights-based moral reasoning and justification',
      parameters: { prompt: 'When is it right to break a law? What principle guides you?', maxResponseLength: 600 },
      measures: ['depth', 'coherence', 'integration'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.65,
    dimensionWeights: {
      depth: 0.4,
      coherence: 0.3,
      integration: 0.3,
    },
    llmRubric:
      'Score for post-conventional/principled moral reasoning. At Orange, right=universal principles that may supersede rules. Depth: can they articulate the principle? Coherence: does reasoning follow from principle? Integration: do they acknowledge costs of breaking rules even when principled?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 240000,
  itemPool: [
    { id: 'moral-orange-01', taskType: 'dilemma', difficulty: 0.2, parameters: { dilemmaType: 'utilitarian-simple', choices: 2, scenarioCount: 2 }, measures: ['depth', 'coherence'] },
    { id: 'moral-orange-02', taskType: 'dilemma', difficulty: 0.25, parameters: { dilemmaType: 'cost-benefit', choices: 2, scenarioCount: 2 }, measures: ['depth', 'coherence'] },
    { id: 'moral-orange-03', taskType: 'dilemma', difficulty: 0.3, parameters: { dilemmaType: 'utilitarian-simple', choices: 3, scenarioCount: 2 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-04', taskType: 'llm_dialogue', difficulty: 0.3, parameters: { prompt: 'Is it right to break a small rule to prevent a larger harm?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'moral-orange-05', taskType: 'dilemma', difficulty: 0.35, parameters: { dilemmaType: 'justice-vs-mercy', choices: 3, scenarioCount: 2 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-06', taskType: 'dilemma', difficulty: 0.4, parameters: { dilemmaType: 'principle-vs-law', choices: 3, scenarioCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-07', taskType: 'llm_dialogue', difficulty: 0.45, parameters: { prompt: 'The greatest good for the greatest number requires sacrificing one. Is that just?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-08', taskType: 'dilemma', difficulty: 0.45, parameters: { dilemmaType: 'cost-benefit', choices: 3, scenarioCount: 3, stakeholders: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-09', taskType: 'dilemma', difficulty: 0.5, parameters: { dilemmaType: 'justice-vs-mercy', choices: 3, scenarioCount: 3, complexity: 'medium' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-10', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'When is it right to break a law? What principle guides you?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-11', taskType: 'dilemma', difficulty: 0.55, parameters: { dilemmaType: 'utilitarian-complex', choices: 4, scenarioCount: 3, uncertainOutcomes: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-12', taskType: 'dilemma', difficulty: 0.6, parameters: { dilemmaType: 'principle-vs-law', choices: 3, scenarioCount: 3, conflictingRights: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-13', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'Two rights are in conflict. How do you weigh them against each other?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-14', taskType: 'dilemma', difficulty: 0.65, parameters: { dilemmaType: 'justice-vs-mercy', choices: 4, scenarioCount: 3, complexity: 'high' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-15', taskType: 'dilemma', difficulty: 0.7, parameters: { dilemmaType: 'principle-vs-principle', choices: 3, scenarioCount: 3, complexity: 'high' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'Your principle demands action that will cause measurable harm. Do you act?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-17', taskType: 'dilemma', difficulty: 0.8, parameters: { dilemmaType: 'utilitarian-complex', choices: 4, scenarioCount: 4, uncertainOutcomes: true, longTermConsequences: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-18', taskType: 'dilemma', difficulty: 0.8, parameters: { dilemmaType: 'justice-vs-mercy', choices: 4, scenarioCount: 4, complexity: 'very-high' }, measures: ['depth', 'coherence', 'integration', 'self_correction'] },
    { id: 'moral-orange-19', taskType: 'dilemma', difficulty: 0.85, parameters: { dilemmaType: 'principle-vs-principle', choices: 4, scenarioCount: 4, complexity: 'very-high' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-orange-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'Every principle you hold leads to harm in this situation. What do you do when reason itself fails?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration', 'self_correction'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Apply moral principle against social pressure',
      task: {
        id: 'mor-ora-probe-agency',
        type: 'dilemma',
        description: 'Apply principle when group disagrees',
        parameters: { dilemmaType: 'principle-vs-group', choices: 2, soloMode: true },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Holds principle with own conviction',
      addictionSignal: 'Applies principle without compassion for context',
      allergySignal: 'Cannot hold principle against opposition',
    },
    communion: {
      description: 'Explain principled reasoning to rule-follower',
      task: {
        id: 'mor-ora-probe-communion',
        type: 'llm_dialogue',
        description: 'Explain why principle matters to a rule-follower NPC',
        parameters: { prompt: 'But the rule is clear. Why would you ever break it?', maxResponseLength: 500 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Explains principle while respecting the rule-follower',
      addictionSignal: 'Dismisses rule-following as inferior',
      allergySignal: 'Abandons principle to avoid disagreement',
    },
    eros: {
      description: 'Face dilemma where principles themselves conflict',
      task: {
        id: 'mor-ora-probe-eros',
        type: 'dilemma',
        description: 'Two valid principles in direct conflict',
        parameters: { dilemmaType: 'principle-vs-principle', choices: 3, complexity: 'high' },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Engages with principle-conflict thoughtfully',
      addictionSignal: 'Paralyzed by conflicting principles',
      allergySignal: 'Refuses to admit principles can conflict',
    },
    agape: {
      description: 'Return to simple rule scenario with full engagement',
      task: {
        id: 'mor-ora-probe-agape',
        type: 'scenario',
        description: 'Return to simple moral rule with presence',
        parameters: { scenarioType: 'clear-rule', responseType: 'choice-plus-text' },
        measures: ['coherence', 'depth'],
      },
      healthyResponse: 'Returns to simple morality with care',
      addictionSignal: 'Refuses simple moral scenarios',
      allergySignal: 'Cannot engage with morality at any level',
    },
  },
};
