import type { AssessmentItem, StageAssessment } from '../types.js';

export const emotionalOrange: StageAssessment = {
  line: 'Emotional',
  stage: 'Orange',
  tasks: [
    {
      id: 'emo-ora-complex',
      type: 'emotion_identification',
      description: 'Identify mixed and complex emotions from scenarios',
      parameters: {
        stimulusType: 'scenario',
        emotionSet: ['bittersweet', 'ambivalence', 'contempt', 'awe', 'nostalgia'],
        trials: 8,
      },
      measures: ['accuracy', 'response_time', 'depth'],
    },
    {
      id: 'emo-ora-regulation',
      type: 'scenario',
      description: 'Choose appropriate emotion regulation strategy',
      parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'suppression', 'expression', 'acceptance'], scenarios: 4 },
      measures: ['depth', 'coherence', 'integration'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.65,
    dimensionWeights: {
      accuracy: 0.2,
      depth: 0.3,
      consistency: 0.2,
      integration: 0.3,
    },
  },
  minimumTrials: 4,
  estimatedDurationMs: 210000,
  itemPool: [
    { id: 'emotional-orange-01', taskType: 'emotion_identification', difficulty: 0.2, parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'ambivalence'], trials: 4 }, measures: ['accuracy', 'response_time'] },
    { id: 'emotional-orange-02', taskType: 'emotion_identification', difficulty: 0.25, parameters: { stimulusType: 'scenario', emotionSet: ['contempt', 'awe'], trials: 4 }, measures: ['accuracy', 'depth'] },
    { id: 'emotional-orange-03', taskType: 'emotion_identification', difficulty: 0.3, parameters: { stimulusType: 'scenario', emotionSet: ['nostalgia', 'ambivalence', 'awe'], trials: 5 }, measures: ['accuracy', 'response_time', 'depth'] },
    { id: 'emotional-orange-04', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'acceptance'], scenarios: 2 }, measures: ['depth', 'coherence'] },
    { id: 'emotional-orange-05', taskType: 'emotion_identification', difficulty: 0.35, parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'contempt', 'nostalgia', 'awe'], trials: 6 }, measures: ['accuracy', 'response_time'] },
    { id: 'emotional-orange-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'suppression', 'expression'], scenarios: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-orange-07', taskType: 'emotion_identification', difficulty: 0.4, parameters: { stimulusType: 'scenario', emotionSet: ['ambivalence', 'contempt', 'awe', 'nostalgia'], trials: 6, timeLimit: 8000 }, measures: ['accuracy', 'response_time', 'depth'] },
    { id: 'emotional-orange-08', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'suppression', 'acceptance', 'expression'], scenarios: 3 }, measures: ['depth', 'coherence'] },
    { id: 'emotional-orange-09', taskType: 'emotion_identification', difficulty: 0.5, parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'ambivalence', 'contempt', 'awe', 'nostalgia'], trials: 8 }, measures: ['accuracy', 'depth'] },
    { id: 'emotional-orange-10', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'suppression', 'expression', 'acceptance'], scenarios: 4, contextual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-orange-11', taskType: 'emotion_identification', difficulty: 0.55, parameters: { stimulusType: 'scenario', emotionSet: ['schadenfreude', 'ennui', 'sublime', 'ambivalence'], trials: 6 }, measures: ['accuracy', 'depth', 'response_time'] },
    { id: 'emotional-orange-12', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'regulation-mismatch', strategies: ['reappraisal', 'suppression', 'expression', 'acceptance'], scenarios: 4 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-orange-13', taskType: 'emotion_identification', difficulty: 0.6, parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'ambivalence', 'contempt', 'awe', 'nostalgia', 'schadenfreude'], trials: 8 }, measures: ['accuracy', 'depth'] },
    { id: 'emotional-orange-14', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'novel-emotion', responseType: 'text', scenarios: 3 }, measures: ['depth', 'integration'] },
    { id: 'emotional-orange-15', taskType: 'emotion_identification', difficulty: 0.7, parameters: { stimulusType: 'micro-expression', emotionSet: ['contempt', 'awe', 'ambivalence'], trials: 8, timeLimit: 5000 }, measures: ['accuracy', 'response_time'] },
    { id: 'emotional-orange-16', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'suppression', 'expression', 'acceptance', 'distancing'], scenarios: 5 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-orange-17', taskType: 'emotion_identification', difficulty: 0.75, parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'ambivalence', 'contempt', 'awe', 'nostalgia', 'sublime', 'ennui'], trials: 10 }, measures: ['accuracy', 'depth', 'consistency'] },
    { id: 'emotional-orange-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'regulation-under-pressure', strategies: ['reappraisal', 'acceptance', 'expression'], scenarios: 4, timeLimit: 6000 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-orange-19', taskType: 'emotion_identification', difficulty: 0.85, parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'ambivalence', 'contempt', 'awe', 'nostalgia', 'schadenfreude', 'sublime'], trials: 10, timeLimit: 5000 }, measures: ['accuracy', 'response_time', 'depth'] },
    { id: 'emotional-orange-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'regulation-novel-context', strategies: ['reappraisal', 'suppression', 'expression', 'acceptance', 'distancing'], scenarios: 5, novelContext: true }, measures: ['depth', 'coherence', 'integration', 'self_correction'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Choose regulation strategy without guidance',
      task: {
        id: 'emo-ora-probe-agency',
        type: 'scenario',
        description: 'Choose emotion regulation strategy independently',
        parameters: { scenarioType: 'regulation-strategy', strategies: ['reappraisal', 'acceptance'], soloMode: true },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Selects strategy with rational confidence',
      addictionSignal: 'Over-regulates, suppresses all emotion',
      allergySignal: 'Cannot choose strategy without external guidance',
    },
    communion: {
      description: 'Help NPC choose regulation strategy',
      task: {
        id: 'emo-ora-probe-communion',
        type: 'llm_dialogue',
        description: 'Help NPC select an emotion regulation strategy',
        parameters: { prompt: 'I feel overwhelmed. What should I do with this feeling?', maxResponseLength: 400 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Guides without imposing, shares knowledge',
      addictionSignal: 'Imposes strategy without listening',
      allergySignal: 'Cannot help others with emotions at all',
    },
    eros: {
      description: 'Face situation requiring novel regulation',
      task: {
        id: 'emo-ora-probe-eros',
        type: 'scenario',
        description: 'Face novel emotional situation requiring creative regulation',
        parameters: { scenarioType: 'novel-emotion', responseType: 'text' },
        measures: ['depth', 'integration'],
      },
      healthyResponse: 'Creates new regulatory approach with curiosity',
      addictionSignal: 'Compulsively seeks novel emotional experiences',
      allergySignal: 'Refuses unfamiliar emotional territory',
    },
    agape: {
      description: 'Return to basic emotion naming with presence',
      task: {
        id: 'emo-ora-probe-agape',
        type: 'emotion_identification',
        description: 'Return to naming basic emotions with full presence',
        parameters: { stimulusType: 'face', emotionSet: ['happy', 'sad', 'angry', 'afraid'], trials: 4 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple naming with grace',
      addictionSignal: 'Refuses simple tasks as beneath them',
      allergySignal: 'Cannot engage with emotion at basic level',
    },
  },
};
