import type { AssessmentItem, StageAssessment } from '../types.js';

export const emotionalRed: StageAssessment = {
  line: 'Emotional',
  stage: 'Red',
  tasks: [
    {
      id: 'emo-red-self-other',
      type: 'emotion_identification',
      description: 'Self-other emotion identification from scenarios',
      parameters: {
        stimulusType: 'scenario',
        emotionSet: ['anger', 'desire', 'excitement', 'frustration'],
        distinguishSelfOther: true,
      },
      measures: ['accuracy', 'response_time', 'consistency'],
    },
    {
      id: 'emo-red-intensity',
      type: 'self_report',
      description: 'Rate emotion intensity on a 1-5 scale',
      parameters: { scale: 5, scenarios: 4 },
      measures: ['depth', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.55,
    dimensionWeights: {
      accuracy: 0.3,
      depth: 0.3,
      consistency: 0.2,
      coherence: 0.2,
    },
  },
  minimumTrials: 3,
  estimatedDurationMs: 150000,
  itemPool: [
    { id: 'emotional-red-01', taskType: 'emotion_identification', difficulty: 0.2, parameters: { stimulusType: 'face', emotionSet: ['anger', 'happiness'], trials: 4 }, measures: ['accuracy', 'response_time'] },
    { id: 'emotional-red-02', taskType: 'emotion_identification', difficulty: 0.25, parameters: { stimulusType: 'face', emotionSet: ['anger', 'sadness', 'happiness'], trials: 5 }, measures: ['accuracy', 'consistency'] },
    { id: 'emotional-red-03', taskType: 'emotion_identification', difficulty: 0.3, parameters: { stimulusType: 'scenario', emotionSet: ['anger', 'desire', 'excitement'], trials: 4 }, measures: ['accuracy', 'depth'] },
    { id: 'emotional-red-04', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'power-emotion', responseType: 'choice', choices: 3 }, measures: ['accuracy', 'coherence'] },
    { id: 'emotional-red-05', taskType: 'emotion_identification', difficulty: 0.35, parameters: { stimulusType: 'scenario', emotionSet: ['anger', 'frustration', 'excitement', 'desire'], distinguishSelfOther: true, trials: 5 }, measures: ['accuracy', 'consistency'] },
    { id: 'emotional-red-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'conflict-emotion', responseType: 'choice-plus-text', choices: 3 }, measures: ['depth', 'coherence'] },
    { id: 'emotional-red-07', taskType: 'emotion_identification', difficulty: 0.4, parameters: { stimulusType: 'voice', emotionSet: ['anger', 'excitement', 'frustration', 'contempt'], trials: 6 }, measures: ['accuracy', 'response_time'] },
    { id: 'emotional-red-08', taskType: 'emotion_identification', difficulty: 0.45, parameters: { stimulusType: 'scenario', emotionSet: ['anger', 'desire', 'frustration', 'excitement', 'contempt'], distinguishSelfOther: true, trials: 6 }, measures: ['accuracy', 'depth'] },
    { id: 'emotional-red-09', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'dominance-emotion', responseType: 'text', maxLength: 200 }, measures: ['depth', 'coherence'] },
    { id: 'emotional-red-10', taskType: 'emotion_identification', difficulty: 0.5, parameters: { stimulusType: 'scenario', emotionSet: ['anger', 'shame', 'pride', 'desire', 'frustration'], distinguishSelfOther: true, trials: 6 }, measures: ['accuracy', 'consistency', 'depth'] },
    { id: 'emotional-red-11', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'mixed-emotion-power', responseType: 'choice-plus-text', choices: 4 }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'emotional-red-12', taskType: 'emotion_identification', difficulty: 0.6, parameters: { stimulusType: 'scenario', emotionSet: ['pride', 'shame', 'contempt', 'envy', 'desire'], distinguishSelfOther: true, trials: 7 }, measures: ['accuracy', 'depth'] },
    { id: 'emotional-red-13', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'betrayal-emotion', responseType: 'text', maxLength: 300 }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'emotional-red-14', taskType: 'emotion_identification', difficulty: 0.65, parameters: { stimulusType: 'scenario', emotionSet: ['rage', 'humiliation', 'triumph', 'jealousy'], distinguishSelfOther: true, trials: 6 }, measures: ['accuracy', 'depth', 'coherence'] },
    { id: 'emotional-red-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'power-loss-emotion', responseType: 'text', maxLength: 300 }, measures: ['depth', 'coherence'] },
    { id: 'emotional-red-16', taskType: 'emotion_identification', difficulty: 0.7, parameters: { stimulusType: 'scenario', emotionSet: ['rage', 'vulnerability', 'triumph', 'shame', 'desire'], distinguishSelfOther: true, trials: 8 }, measures: ['accuracy', 'consistency', 'depth'] },
    { id: 'emotional-red-17', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'complex-power-emotion', responseType: 'text', maxLength: 400 }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'emotional-red-18', taskType: 'emotion_identification', difficulty: 0.8, parameters: { stimulusType: 'scenario', emotionSet: ['ambivalence', 'bittersweet', 'awe', 'contempt', 'vulnerability'], distinguishSelfOther: true, trials: 8 }, measures: ['accuracy', 'depth', 'coherence'] },
    { id: 'emotional-red-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'ego-threat-emotion', responseType: 'text', maxLength: 400 }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'emotional-red-20', taskType: 'emotion_identification', difficulty: 0.9, parameters: { stimulusType: 'scenario', emotionSet: ['ambivalence', 'vulnerability', 'awe', 'shame', 'desire', 'rage'], distinguishSelfOther: true, trials: 10 }, measures: ['accuracy', 'depth', 'coherence', 'consistency'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Identify your own emotion without group consensus',
      task: {
        id: 'emo-red-probe-agency',
        type: 'emotion_identification',
        description: 'Identify own emotion independently without external validation',
        parameters: { stimulusType: 'scenario', distinguishSelfOther: true, soloMode: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Names own emotion with confidence',
      addictionSignal: 'Dismisses others emotional reality entirely',
      allergySignal: 'Cannot name emotion without checking with others',
    },
    communion: {
      description: 'Help NPC identify their emotion',
      task: {
        id: 'emo-red-probe-communion',
        type: 'llm_dialogue',
        description: 'Help an NPC character identify what they are feeling',
        parameters: { prompt: 'I feel something but I do not know what it is. Can you help?', maxResponseLength: 300 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Attunes to other without losing own emotional ground',
      addictionSignal: 'Over-merges with other, loses own feeling',
      allergySignal: 'Refuses emotional engagement with other',
    },
    eros: {
      description: 'Attempt to identify a complex/mixed emotion',
      task: {
        id: 'emo-red-probe-eros',
        type: 'emotion_identification',
        description: 'Identify a complex or mixed emotion beyond basic set',
        parameters: { stimulusType: 'scenario', emotionSet: ['bittersweet', 'ambivalence', 'awe'], distinguishSelfOther: true },
        measures: ['accuracy', 'depth'],
      },
      healthyResponse: 'Reaches toward emotional complexity with curiosity',
      addictionSignal: 'Compulsively seeks intensity, cannot tolerate calm',
      allergySignal: 'Refuses emotional complexity, stays with basics only',
    },
    agape: {
      description: 'Return to basic emotion naming with care',
      task: {
        id: 'emo-red-probe-agape',
        type: 'emotion_identification',
        description: 'Return to naming simple basic emotions with full presence',
        parameters: { stimulusType: 'scenario', emotionSet: ['happy', 'sad', 'angry', 'afraid'], distinguishSelfOther: false },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple naming with full engagement',
      addictionSignal: 'Refuses simple tasks as beneath them',
      allergySignal: 'Cannot engage with emotion even at simple level',
    },
  },
};
